### ISSUE TITLE
rails 4.2.0rc1 can't modify frozen ActiveRecord::LazyAttributeHash

### ISSUE THREAD

**Issue by testbrian** [ruby-grape/grape-active_model_serializers#32]
When using grape active model serializers with grape API I updated from Rails 4.2.0.beta4 to 4.2.0rc1 and suddenly all actions that return a destroyed object (`product.destroy`)result in
`can't modify frozen ActiveRecord::LazyAttributeHash`
The fix was to specify a serializer or return something other than the object which was frozen after destroy.
```
Exception: RuntimeError: can't modify frozen ActiveRecord::LazyAttributeHash
  0: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/attribute_set/builder.rb:79:in `materialize'
  1: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/attribute_set/builder.rb:23:in `select'
  2: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/attribute_set.rb:70:in `initialized_attributes'
  3: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/attribute_set.rb:18:in `to_hash'
  4: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/attribute_methods.rb:284:in `attributes'
  5: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.0.rc1/lib/active_model/serialization.rb:100:in `serializable_hash'
  6: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/serialization.rb:17:in `serializable_hash'
  7: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activemodel-4.2.0.rc1/lib/active_model/serializers/json.rb:99:in `as_json'
  8: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/json/encoding.rb:34:in `encode'
  9: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/json/encoding.rb:21:in `encode'
 10: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
 11: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/formatter/json.rb:6:in `call'
 12: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-active_model_serializers-1.2.1/lib/grape-active_model_serializers/formatter.rb:11:in `call'
 13: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:33:in `block in after'
 14: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:32:in `collect'                                                                                                                           [100/5640]
 15: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:32:in `after'
 16: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:25:in `call!'
 17: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
 18: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:24:in `call!'
 19: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
 20: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:24:in `call!'
 21: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
 22: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/error.rb:27:in `block in call!'
 23: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `catch'
 24: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `call!'
 25: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
 26: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/head.rb:13:in `call'
 27: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/builder.rb:153:in `call'
 28: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rollbar-1.1.0/lib/rollbar/middleware/rack/builder.rb:8:in `call_with_rollbar'
 29: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/endpoint.rb:172:in `call!'
 30: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/endpoint.rb:160:in `call'
 31: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
 32: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
 33: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
 34: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
 35: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
 36: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/api.rb:128:in `call'
 37: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/api.rb:43:in `call!'
 38: /Users/brian/.rvm/gems/ruby-2.1.5/gems/grape-0.9.0/lib/grape/api.rb:39:in `call'
 39: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/routing/mapper.rb:51:in `serve'
 40: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
 41: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/journey/router.rb:30:in `each'
 42: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/journey/router.rb:30:in `serve'
 43: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/routing/route_set.rb:800:in `call'
 44: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
 45: /Users/brian/.rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:404:in `call_app!'
 46: /Users/brian/.rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:262:in `mock_call!'
 47: /Users/brian/.rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:181:in `call!'
 48: /Users/brian/.rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
 49: /Users/brian/.rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
 50: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rollbar-1.1.0/lib/rollbar/middleware/rails/rollbar_request_store.rb:13:in `call'
 51: /Users/brian/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
 52: /Users/brian/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
 53: /Users/brian/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
 54: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/etag.rb:24:in `call'
 55: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/conditionalget.rb:38:in `call'
 56: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/head.rb:13:in `call'
 57: /Users/brian/.rvm/gems/ruby-2.1.5/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
 58: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 59: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/flash.rb:260:in `call'
 60: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/session/abstract/id.rb:225:in `context'
 61: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0.beta2/lib/rack/session/abstract/id.rb:220:in `call'
 62: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
 63: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/query_cache.rb:36:in `call'
 64: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
 64: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'                                                                                   [50/5640]
 65: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 66: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/callbacks.rb:88:in `call'
 67: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
 68: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
 69: /Users/brian/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/callbacks.rb:81:in `run_callbacks'
 70: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 71: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 72: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 73: /Users/brian/.rvm/gems/ruby-2.1.5/gems/rollbar-1.1.0/lib/rollbar/middleware/rails/show_exceptions.rb:19:in `call_with_rollbar'
 74: /Users/brian/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 75: /Users/brian/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/rack/logger.rb:38:in `call_app'
```

**Comment by nadeemyasin61** [comment]
@siong1987 any update here. Getting same error with grape api and rails 4.2.0rc1

**Comment by testbrian** [comment]
I had to specify serializer to fix.. It seems it isn't able to figure out what serializer to use?
```
         delete '/', serializer: ::CommentsSerializer, root: false do
         end
```

**Comment by dblock** [comment]
@testbrian Write a spec with your repro?

**Comment by testbrian** [comment]
@nadeemyasin61 Could you reproduce with a spec?

**Comment by drn** [comment]
closing this issue as it is multiple years old and the codebase has changed since then. if you can test this against master and repro the issue, please create another issue.

**Comment by testbrian** [comment]
👍
