### ISSUE TITLE
Test failures about Hash#deep_dup missing

### ISSUE THREAD

**Issue by olleolleolle** [ruby-grape/grape-active_model_serializers#90]
This Issue is to mark the presence of a CI failure like

https://travis-ci.com/olleolleolle/grape-active_model_serializers/jobs/173305202

```
#render
  with meta key
    includes meta key and content (FAILED - 1)
  with a custom meta_key
    includes the custom meta key name (FAILED - 2)
    ignores a lonely meta_key (FAILED - 3)
  junk keys
    ignores junk keys (FAILED - 4)
    ignores empty meta_key (FAILED - 5)
    ignores empty meta (FAILED - 6)
```

<details>

```
  1) #render with meta key includes meta key and content
     Failure/Error:
       ::ActiveModelSerializers::Adapter.create(
         serializer, options
       ).to_json
     
     NoMethodError:
       undefined method `deep_dup' for {}:Hash
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model/serializer.rb:350:in `block in associations'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model/serializer.rb:406:in `each'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model/serializer.rb:406:in `each_with_object'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model/serializer.rb:406:in `associations_hash'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model/serializer.rb:367:in `serializable_hash'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model_serializers/adapter/attributes.rb:7:in `serializable_hash'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model_serializers/adapter/json.rb:6:in `serializable_hash'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/active_model_serializers-0.10.8/lib/active_model_serializers/adapter/base.rb:59:in `as_json'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:35:in `encode'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:22:in `encode'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:41:in `to_json'
     # ./lib/grape-active_model_serializers/formatter.rb:12:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:33:in `block in after'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:32:in `collect'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/formatter.rb:32:in `after'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/base.rb:25:in `call!'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/error.rb:27:in `block in call!'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `catch'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `call!'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:153:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/endpoint.rb:172:in `call!'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/endpoint.rb:160:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/api.rb:128:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/api.rb:43:in `call!'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/grape-0.9.0/lib/grape/api.rb:39:in `call'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /home/travis/.rvm/gems/ruby-2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # ./spec/features/grape-active_model_serializers/render_spec.rb:18:in `get_resource_with'
     # ./spec/features/grape-active_model_serializers/render_spec.rb:24:in `block (3 levels) in <top (required)>'
```

</details>

**Comment by dblock** [comment]
Looks legit because of some dependency version update. Appreciate a fix.

**Comment by mateusnava** [comment]
Any updates?
